### PR TITLE
[WIP] Fix electron-webrtc tests

### PR DESCRIPTION
**Pull request by RationalCoding**
The `onclose` event was not being fired, so two of the tests in the stream suite were failing on electron-webrtc. Oddly enough, I could only reproduce this inside Travis.

Closing the channel before closing the pc seems to make this error disappear. I haven't seen in it the 5 runs since, where I was hitting it every time before.

I think we should figure out why electron-webrtc has this behaviour, but I'm at a loss at how to reproduce outside of Travis.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Hmm... test is still failing on Travis

**Comment by RationalCoding** [comment]
Now it's throwing ECONNRESET. That's different...

**Comment by RationalCoding** [comment]
The ECONNRESET is thrown by electron-eval abruptly closing the TCP connection to the electron daemon. I'm not sure why this isn't caught by that module considering that's an expected error on closing the daemon, but they seem aware of the issue.

I've silenced the error as it has nothing to do with simple-peer or normal usage of electron-webrtc.

**Comment by RationalCoding** [comment]
electron-webrtc tests pass now. Not sure what is going on with the new airtap tests though.

**Comment by RationalCoding** [comment]
Still seeing ECONNRESET... seems we'll have to fix the problem through electron-eval.

**Pull request merged**
