### PR TITLE
Detect webkitRTCPeerConnection and fallback to standard

### PR DESCRIPTION
**Pull request by bkonkle**
See #116 for context. This detects `webkitRTCPeerConnection` to determine if Chrome's non-standard `getStats` signature needs to be used, and falls back to the standard signature that Mozilla and `react-native-webrtc` use.

### CODE REVIEW

**Comment by bkonkle** [comment]
Tested in React Native iOS v0.39.2, and the latest Electron. I don't have a web project to test it with at the moment.

**Comment by feross** [comment]
I was actually just editing this code today to fix a warning in Firefox (#118). Your PR makes a good point though, we should only special-case Chrome and fallback to the standard behavior. I'll update that.

**Comment by feross** [comment]
@bkonkle Can you test 6.1.2 and see if your issue is resolved?

**Comment by bkonkle** [comment]
6.1.3 Works great for my use case. Thanks!

**Comment by feross** [comment]
Great!

**Pull request closed without merging**
