### PR TITLE
Fix re-offer: Wait for async setLocalDescription

### PR DESCRIPTION
**Pull request by feross**
Supercedes PR: https://github.com/feross/simple-peer/pull/173

See @feross's comments for context about this commit.

### CODE REVIEW

**Comment by feross** [comment]
cc @MatthieuLemoine

**Comment by feross** [comment]
Released as 8.1.0.

**Comment by MatthieuLemoine** [comment]
Yes it works ! 🎉

**Comment by feross** [comment]
@MatthieuLemoine nice!

**Pull request merged**
