### PR TITLE
add support for impls that do not support getStats, closes #44

### LINKED ISSUE #44: support lack of pc.getStats
right now this doesn't work on ios since webrtc getStats isn't implemented yet. this is being used in the internals of simple-peer to get local/remote address - is this needed or anything other than debug?

### PR DESCRIPTION
**Pull request by contra**
this seems like it was for debugging but it prevents some implementations from working (iosrtc tested)

### CODE REVIEW

**Comment by contra** [comment]
Tests failing due to no saucelabs credentials, not because of an actual failure ^

**Comment by contra** [comment]
@feross Sorry to do this, but *ping* - hate to keep running off a github fork in production

**Comment by feross** [comment]
Looks good to me! Released as 5.11.6.

Added you as a github collaborator. Feel free to contribute as you see fit in the future, per the [guidelines](https://github.com/feross/webtorrent/blob/master/CONTRIBUTING.md#webtorrent-is-an-open-open-source-project) here.

**Comment by contra** [comment]
@feross Thanks! Would you like me to ping you when a release is needed?

**Comment by feross** [comment]
No need for that. I just added you as an npm owner :+1: 

@mafintosh, @maxogden, and @substack - you're owners now too.

**Pull request merged**
