### PR TITLE
Fix renegotiate signal event firing on first negotiation

### LINKED ISSUE #670: Two peers sending video/audio leads to immediate renegotiation
Using `simple-peer` in a relatively simple setup. Seeing the non-initiator peer immediately request renegotiation even though everything is specified upfront in the constructor. I see two offer/answers sent from the initiator peer.

Here's my setup: Two peers, each initialized with the `stream` option, so `addTrack()` is called twice (once for video, once for audio) internally in the constructor. For the non-initiator peer, `this._isNegotiating` is already `true` because of this line in the constructor:

https://github.com/feross/simple-peer/blob/90c3dfd35ef3727b17e7b52b1c45cbc84d6ff416/index.js#L89

Therefore, for the non-initiator peer, the calls to `this._needsNegotiation()` in response to `addTrack()` cause a negotiation to be immediately queued. Once the connection is stable it triggers the re-negotiation. 

Is this intentional?

### PR DESCRIPTION
**Pull request by t-mullen**
Fixes #670. See also #671.

### CODE REVIEW

**Comment by f-r00t** [comment]
This patch fixed issues I was having with "renegiotate" triggering every time a connection was established between two peers.

**Comment by abdatta** [comment]
Is this gonna be merged soon? I'm facing the same issue right now with simple peer.

**Comment by yaplusplus** [comment]
It would be so nice to have this PR reviewed and merged
@feross 🙏

**Review by feross — APPROVED** [review]
LGTM!

**Comment by feross** [comment]
Released as 9.8.0

**Pull request merged**
