### PR TITLE
Update docs to reflect actual STUN URL

### PR DESCRIPTION
**Pull request by pastudan**
Just noticed this was out of date.

### CODE REVIEW

**Comment by pastudan** [comment]
Also, I'm just curious why you're not using the google one. Against Google ToS? And are you footing the bill for this STUN server?

**Comment by nazar-pc** [comment]
You have probably looked at the wrong place, here are actual STUN servers used by default:
https://github.com/feross/simple-peer/blob/f3cb23e8fc867a17fc45e38505996d601b90a595/index.js#L151-L160

**Comment by nazar-pc** [comment]
Also readme is just an example, you can place any STUN server you want there or omit altogether and use defaults

**Comment by pastudan** [comment]
Oops! Yes I was looking at an [old commit](https://github.com/feross/simple-peer/commit/822f2ae3b1394d226b18523810d2007b0b5c934c). Sorry about that.

**Comment by pastudan** [comment]
As for my rationale for updating... the readme says these are the defaults. Not a big deal, but its probably good to give people a heads up that by using this package their users will be connecting to Google and Twilio servers.

**Comment by feross** [comment]
@pastudan Thanks, updated the readme.

**Pull request closed without merging**
